config:
    shim:
        'moment':
            exports:
                - 'moment'
        'numeral':
            exports:
                - 'numeral'
        'orolocale/js/formatter/number':
            deps:
                - 'numeral'
                - 'orolocale/js/locale-settings'
    map:
        '*':
            'moment': 'orolocale/js/moment-l10n'
        'orolocale/js/moment-l10n':
            'moment': 'moment'

    paths:
        'moment': 'bundles/orolocale/lib/moment/moment.js'
        'numeral': 'bundles/orolocale/lib/numeral.js'
        'orolocale/js/locale-settings': 'bundles/orolocale/js/locale-settings.js'
        'orolocale/js/locale-settings/data': '../js/oro.locale_data.js'
        'orolocale/js/formatter/name': 'bundles/orolocale/js/formatter/name.js'
        'orolocale/js/formatter/address': 'bundles/orolocale/js/formatter/address.js'
        'orolocale/js/formatter/number': 'bundles/orolocale/js/formatter/number.js'
        'orolocale/js/formatter/datetime': 'bundles/orolocale/js/formatter/datetime.js'
        'orolocale/js/moment-l10n': 'bundles/orolocale/js/moment-l10n.js'
