parameters:
    oro_locale.settings.class: Oro\Bundle\LocaleBundle\Model\LocaleSettings
    oro_locale.form.type.name_format.type.class: Oro\Bundle\LocaleBundle\Form\Type\NameFormatType

    oro_locale.format_converter.date_time.registry.class: Oro\Bundle\LocaleBundle\Converter\DateTimeFormatConverterRegistry
    oro_locale.format_converter.date_time.intl.class: Oro\Bundle\LocaleBundle\Converter\IntlDateTimeFormatConverter
    oro_locale.format_converter.date_time.moment.class: Oro\Bundle\LocaleBundle\Converter\MomentDateTimeFormatConverter

    oro_locale.formatter.name.class: Oro\Bundle\LocaleBundle\Formatter\NameFormatter
    oro_locale.formatter.address.class: Oro\Bundle\LocaleBundle\Formatter\AddressFormatter
    oro_locale.formatter.date_time.class: Oro\Bundle\LocaleBundle\Formatter\DateTimeFormatter
    oro_locale.formatter.number.class: Oro\Bundle\LocaleBundle\Formatter\NumberFormatter

    oro_locale.twig.date_format.class: Oro\Bundle\LocaleBundle\Twig\DateFormatExtension
    oro_locale.twig.locale.class: Oro\Bundle\LocaleBundle\Twig\LocaleExtension

services:
    oro_locale.settings:
        class: %oro_locale.settings.class%
        arguments:
            - @oro_config.global
        calls:
            - [addNameFormats, [%oro_locale.format.name%]]
            - [addAddressFormats, [%oro_locale.format.address%]]
            - [addLocaleData, [%oro_locale.locale_data%]]

    oro_locale.form.type.name_format.type:
        class: %oro_locale.form.type.name_format.type.class%
        arguments:
            - @oro_locale.settings
        tags:
            - { name: form.type, alias: "oro_name_format" }
            
    oro_locale.format_converter.date_time.registry:
        class: %oro_locale.format_converter.date_time.registry.class%

    oro_locale.format_converter.date_time.intl:
        class: %oro_locale.format_converter.date_time.intl.class%
        arguments:
            - @oro_locale.settings
        tags:
            - { name: oro_locale.format_converter.date_time, alias: intl }

    oro_locale.format_converter.date_time.moment:
        class: %oro_locale.format_converter.date_time.moment.class%
        arguments:
            - @oro_locale.settings
        tags:
            - { name: oro_locale.format_converter.date_time, alias: moment }

    oro_locale.formatter.name:
        class: %oro_locale.formatter.name.class%
        arguments:
            - @oro_locale.settings

    oro_locale.formatter.address:
        class: %oro_locale.formatter.address.class%
        arguments:
            - @oro_locale.settings
            - @oro_locale.formatter.name

    oro_locale.formatter.date_time:
        class: %oro_locale.formatter.date_time.class%
        arguments:
            - @oro_locale.settings

    oro_locale.formatter.number:
        class: %oro_locale.formatter.number.class%
        arguments:
            - @oro_locale.settings

    oro_locale.twig.date_format:
        class: %oro_locale.twig.date_format.class%
        arguments:
            - @oro_locale.format_converter.date_time.registry
        tags:
            - { name: twig.extension }

    oro_locale.twig.locale:
        class: %oro_locale.twig.locale.class%
        arguments:
            - @oro_locale.settings
        tags:
            - { name: twig.extension }
