oro_system_configuration:
    groups:
        localization:
            title: 'Localization'
            icon:  'icon-flag'

        locale_settings:
            title: 'Localization options'

        locale_options:
            title: 'Formatting options'

    fields:
        oro_locale.language:
            type: locale
            priority: 70
            options:
                label: 'Language'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.locale:
            type: locale
            priority: 60
            options:
                label: 'Locale'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.timezone:
            type: timezone
            priority: 50
            options:
                label: 'Timezone'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.country:
            type: country
            priority: 40
            options:
                label: 'Country'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.currency:
            type: currency
            priority: 30
            options:
                label: 'Currency'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.format_address_by_address_country:
            type: oro_config_checkbox
            priority: 20
            options:
                label: 'Format address by address country'
                required: true

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                priority: 254
                                children:
                                    locale_settings:
                                        priority: 100
                                        children:
                                            - oro_locale.language
                                            - oro_locale.country
                                            - oro_locale.currency
                                            - oro_locale.timezone
                                    locale_options:
                                        priority: 50
                                        children:
                                            - oro_locale.locale
                                            - oro_locale.format_address_by_address_country
