oro_system_configuration:
    groups:
        localization:
            title: 'Localization'
            icon:  'icon-flag'

        locale_settings:
            title: 'Localization settings'

        locale_options:
            title: 'Locale options'

    fields:
        oro_locale.language:
            type: language
            priority: 60
            options:
                label: 'Language'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.locale:
            type: locale
            priority: 50
            options:
                label: 'Locale'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.timezone:
            type: timezone
            priority: 40
            options:
                label: 'Timezone'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.default_currency:
            type: currency
            priority: 30
            options:
                label: 'Default currency'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.name_format:
            type: text
            priority: 20
            options:
                label: 'Name format'
                required: true
                #tooltip: 'Available variables:<br> %%firstname%%, %%lastname%%'
                constraints:
                    - NotBlank: ~

        oro_locale.address_format:
            type: textarea
            priority: 10
            options:
                label: 'Address format'
                required: true
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                priority: 254
                                children:
                                    locale_settings:
                                        priority: 100
                                        children:
                                            - oro_locale.language
                                            - oro_locale.locale
                                            - oro_locale.default_currency
                                            - oro_locale.timezone
                                    locale_options:
                                        priority: 50
                                        children:
                                            - oro_locale.name_format
                                            - oro_locale.address_format