oro_system_configuration:
    groups:
        localization:
            title: 'Localization'
            icon:  'icon-time'

        locale_options:
            title: 'Locale options'

        number_formats:
            title: 'Nubmer formats'

    fields:
        oro_locale.locale:
            type: locale
            options:
                label: 'Locale'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.timezone:
            type: timezone
            priority: 253
            options:
                label: 'Timezone'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.default_currency:
            type: currency
            options:
                label: 'Default currency'
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.date_format:
            type: choice
            priority: 255
            options:
                label: 'Date format'
                required: true
                choices:
                      "MM/dd/yy":   "MM/dd/yy"
                      "dd.MM.yyyy": "dd.MM.yyyy"
                      "dd.MM.yy":   "dd.MM.yy"
                      "d.M.yy":     "d.M.yy"
                      "dd/MM/yy":   "dd/MM/yy"
                      "yy/MM/dd":   "yy/MM/dd"
                      "yyyy-MM-dd": "yyyy-MM-dd"
                constraints:
                    - NotBlank: ~

        oro_locale.time_format:
            type: choice
            priority: 254
            options:
                label: 'Time format'
                required: true
                choices:
                      "H:mm":  "H:mm"
                      "HH:mm": "HH:mm"
                constraints:
                    - NotBlank: ~

        oro_locale.decimal_symbol:
            type: text
            options:
                label: 'Decimal symbol'
                required: true
                constraints:
                    - NotBlank: ~
                    - Length:   1

        oro_locale.thousands_separator:
            type: text
            options:
                label: '1000s separator'
                required: false
                constraints:
                    - Length:
                        max: 1

        oro_locale.number_of_decimals:
            type: text
            options:
                label: 'Number of digits after decimal'
                required: true
                constraints:
                    - NotBlank: ~
                    - Length:   1
                    - Regex:    "/^[0-9]{1}$/"
                    - Range:
                        min:    0

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                priority: 254
                                children:
                                    locale_options:
                                        children:
                                            - oro_locale.locale
                                            - oro_locale.timezone
                                            - oro_locale.default_currency
                                            - oro_locale.date_format
                                            - oro_locale.time_format
                                    number_formats:
                                        children:
                                            - oro_locale.decimal_symbol
                                            - oro_locale.thousands_separator
                                            - oro_locale.number_of_decimals
