config:
    shim:
        'moment':
            exports:
                - 'moment'
        'numeral':
            exports:
                - 'numeral'

    paths:
        'moment': 'bundles/orolocale/lib/moment/moment.js'
        'numeral': 'bundles/bowerassets/numeral/numeral.js'
        'orolocale/js/locale-settings/data': '../js/oro.locale_data.js'
